import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { registro_incidencias_pages } from "./registro-incidencias.pages.ts";
import { registro_incidencias_tables } from "./registro-incidencias.tables.ts";

export const registro_incidencias_module = define_module({
  resource: "registro-incidencias",
  labels: {
    singular: "Registro de incidencias",
    plural: "Registro de incidencias",
    read: "Ver Registro de incidencias",
    write: "Editar Registro de incidencias",
  },
  routes: define_crud({
    resource: "registro-incidencias",
    table: "registro_incidencias",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "registro",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      alumno_id: { type: "string", search: true },
      grupo_id: { type: "string", search: true },
      registro_asistencia_id: { type: "string", search: true },
      lista_asistencia_id: { type: "string", search: true },
      materia_id: { type: "string", search: true },
      grado_escolar_id: { type: "string", search: true },
      escuela_id: { type: "string", search: true },
      tipo: { type: "string", search: true },
      justificada: { type: "boolean" },
      evidencia: { type: "string", search: true },
      fecha_asistencia: { type: "string", search: true },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: registro_incidencias_tables,
  pages: registro_incidencias_pages,
  menu: [
    {
      id: "control-escolar.alumnos",
      label: "Alumnos",
      order: 0,
      pageId: "control-escolar.alumnos",
      path: "alumnos",
      permission: "subject.control-escolar.alumnos.read",
      icon: "document",
    },
    {
      id: "control-escolar.grados-escolares",
      label: "Grados escolares",
      order: 1,
      pageId: "control-escolar.grados-escolares",
      path: "grados-escolares",
      permission: "subject.control-escolar.grados-escolares.read",
      icon: "document",
    },
    {
      id: "control-escolar.ciclos-escolares",
      label: "Ciclos escolares",
      order: 2,
      pageId: "control-escolar.ciclos-escolares",
      path: "ciclos-escolares",
      permission: "subject.control-escolar.ciclos-escolares.read",
      icon: "document",
    },
    {
      id: "control-escolar.materias",
      label: "Materias",
      order: 3,
      pageId: "control-escolar.materias",
      path: "materias",
      permission: "subject.control-escolar.materias.read",
      icon: "document",
    },
    {
      id: "control-escolar.escuelas",
      label: "Escuelas",
      order: 4,
      pageId: "control-escolar.escuelas",
      path: "escuelas",
      permission: "subject.control-escolar.escuelas.read",
      icon: "document",
    },
    {
      id: "control-escolar.grupo",
      label: "Grupos",
      order: 5,
      pageId: "control-escolar.grupo",
      path: "grupo",
      permission: "subject.control-escolar.grupo.read",
      icon: "document",
    },
    {
      id: "control-escolar.aulas",
      label: "Aulas",
      order: 5,
      pageId: "control-escolar.aulas",
      path: "aulas",
      permission: "subject.control-escolar.aulas.read",
      icon: "document",
    },
    {
      id: "control-escolar.horarios",
      label: "Horarios",
      order: 6,
      pageId: "control-escolar.horarios",
      path: "horarios",
      permission: "subject.control-escolar.horarios.read",
      icon: "document",
    },
    {
      id: "control-escolar.registro-asistencias",
      label: "Registro de asistencias",
      order: 7,
      pageId: "control-escolar.registro-asistencias",
      path: "registro-asistencias",
      permission: "subject.control-escolar.registro-asistencias.read",
      icon: "document",
    },
    {
      id: "control-escolar.lista-asistencia",
      label: "Listas de asistencia",
      order: 7,
      pageId: "control-escolar.lista-asistencia",
      path: "lista-asistencia",
      permission: "subject.control-escolar.lista-asistencia.read",
      icon: "document",
    },
    {
      id: "control-escolar.registro-incidencias",
      label: "Registro de incidencias",
      order: 8,
      pageId: "control-escolar.registro-incidencias",
      path: "registro-incidencias",
      permission: "subject.control-escolar.registro-incidencias.read",
      icon: "document",
    }
    ],
});
